### ISSUE TITLE
Quick issue with parse loci

### ISSUE THREAD

**Issue by izakbed** [dportik/SuperCRUNCH#5]
Hi! Thanks for the tool I have recently come across it and found it very pertinent to my work. However, I am getting a small error when running parse loci even if all of the inputs seem to be proper according to the guide I still get this error. 

Traceback (most recent call last):
  File "Parse_Loci.py", line 508, in <module>
    main()
  File "Parse_Loci.py", line 497, in main
    search_runner(species, loci_info, sql_db_name, records, args.no_subspecies, args.exclude)
  File "Parse_Loci.py", line 463, in search_runner
    accessions = perform_searches(cur, l, spseq, species, exclude_accs)
  File "Parse_Loci.py", line 318, in perform_searches
    terms = prep_terms(l)
  File "Parse_Loci.py", line 311, in prep_terms
    padded = [" {} ".format(t) for t in l[1]]
IndexError: list index out of range

Any idea what is going on?

Thanks for the help,
Izak

**Comment by dportik** [comment]
Hi Izak,
Sorry to hear you are having trouble with this module. 

Based on the error you are reporting, it appears that the issue is your locus search terms file. The script does not seem to be able to detect multiple columns in this input file. Does your search terms file have three columns (locus name, locus abbreviation, locus description), which are tab-delimited? If that is not the issue, I won't be able to help unless I see the search terms file you are trying to use. You can either paste the contents here or attach the file, and I can try to help further.
